version: '3'
services:
  gateway:
    build: ./gateway
    ports:
      - "8080:8080" 
    environment:
            #      - SERVER_PORT=8080
      - MONGO_HOST=mongodb
      - KAFKA_HOST=kafka
    depends_on:
      - kafka
      - mongodb

  urlshortener:
    build: ./urlShortener
    ports:
      - "8081:8081" 
    environment:
      - SERVER_PORT=8081
      - MYSQL_HOST=mysqldb
      - KAFKA_HOST=kafka
    depends_on:
      - kafka
      - mysqldb

  metrics:
    build: ./metrics
    ports:
      - "8082:8082" 
    environment:
      - SERVER_PORT=8082
      - MONGO_HOST=mongodb
      - KAFKA_HOST=kafka
    depends_on:
      - kafka
      - mongodb

  zookeeper:
    image: zookeeper:3.7.2
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: bitnami/kafka:3.3.2
    container_name: kafka
    depends_on:
      - zookeeper
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - ALLOW_PLAINTEXT_LISTENER=yes
    ports:
      - "9092:9092"

  mysqldb:
    image: mysql:latest
    container_name: mysqldb
    volumes:
      - url_db_vol:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_USER=db-user
      - MYSQL_PASSWORD=db-pass
      - MYSQL_DATABASE=urlShortener

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
  url_db_vol:

