spring:
  cloud:
    gateway:
      routes:
        - id: other_route
          uri: http://localhost:8082
          predicates:
            - Path=/api/url/{urlString}/metrics*
        - id: api_route
          uri: http://localhost:8081
          predicates:
            - Path=/**
  data:
    mongodb:
      uri: mongodb://localhost:27017/auth
  kafka:
    bootstrap-servers: localhost:9092
server:
  port: 8080

api-gateway:
    jwt:
        secret: lkajdflasjdflaksjdflasjdflajsdflkasjdflasjflajsdlfkadsjlfajsdlfkjaldfjlasdjf
        expiration: 86400000
    metrics-topic: metrics-tp


